global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'encurtador-url'
    static_configs:
      - targets:
          - app1:8080
          - app2:8080
          - app3:8080
          - app4:8080
          - app5:8080
    metrics_path: /metrics
